---
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "wordpress"
http_host: "wordpress"
http_conf: "wordpress.conf"
http_port: "80"
db_host: "172.31.36.77"
db_port: "3306"
wordpress_host: "172.31.41.194"
