---
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "wordpress"
mysql_ip: "172.31.36.77"
http_host: "wordpress"
http_conf: "wordpress.conf"
wordpress_ip: "172.31.41.194"
